plugin: openapi
specFile: openapi.yml

resources:
  - path: "/decisionanalytics/crosscore/cc_mock_route/3"
    method: post
    requestBody:
      operator: Contains
      value: Manthrope
    response:
      statusCode: 200
      scriptFile: useFraudScoreJsonFile.groovy

  - path: "/decisionanalytics/crosscore/cc_mock_route/3"
    method: post
    requestBody:
      operator: Contains
      value: Hurst
    response:
      statusCode: 200
      scriptFile: useFraudScoreJsonFile.groovy

  - path: "/decisionanalytics/crosscore/cc_mock_route/3"
    method: post
    requestBody:
      operator: Contains
      value: Nohope
    response:
      statusCode: 200
      scriptFile: useFraudScoreStopJsonFile.groovy

  - path: "/decisionanalytics/crosscore/cc_mock_route/3"
    method: post
    requestBody:
      operator: Contains
      value: Nodec
    response:
      statusCode: 200
      scriptFile: useFraudScoreNoDecisionJsonFile.groovy

  - path: "/decisionanalytics/crosscore/cc_mock_route/3"
    method: post
    response:
      statusCode: 200
      scriptFile: useFraudScoreContinueJsonFile.groovy

  - path: "/decisionanalytics/crosscore/cc_mock_route/3"
    method: post
    requestBody:
      operator: Contains
      value: Thinfile
    response:
      statusCode: 200
      scriptFile: useFraudScoreJsonFile.groovy

  - path: "/decisionanalytics/crosscore/cc_mock_route/3"
    method: post
    requestBody:
      operator: Contains
      value: Refer
    response:
      statusCode: 200
      file: data/fraudScoreReferResponse.json
