FROM outofcoffee/imposter-distroless:4.9.0@sha256:28cf00475da841086c16281b2230d6f464c9962d745b5b740fb24ab089fffdec

COPY ./hmpo-config.yaml /opt/imposter/config/hmpo-config.yaml
COPY ./openapi.yml /opt/imposter/config/openapi.yml
COPY ./data/ /opt/imposter/config/data/
