FROM outofcoffee/imposter:4.9.0@sha256:d28ed1a752392454aad04443a72161fd28c36f271e04379b2a185798e8cbf10d

COPY ./hmpo-config.yaml /opt/imposter/config/hmpo-config.yaml
COPY ./openapi.yml /opt/imposter/config/openapi.yml
COPY ./data/ /opt/imposter/config/data/
