openapi: 3.0.0
info:
  title: Notifications API
  description: Backwards engineered and limited to what we need to mock; deprecate if notifications provide an api spec
  version: 0.1.0
servers:
  - url: http://localhost:8080
    description: Local Imposter server
x-json-schema-faker:
  alwaysFakeOptionals: false
  optionalsProbability: 0.5
  fillProperties: true
paths:
  /api/v1/users/current:
    get:
      summary: Get current user
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "401":
          description: Error
  /api/v1/digital-lpas/{uid}:
    parameters:
      - name: uid
        in: path
        description: The UID of the case
        required: true
        schema:
          type: string
          nullable: true
          pattern: (M(-[A-Z0-9]{4}){3})
    get:
      summary: Get an LPA
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CombinedLpa"
        "401":
          description: Error
  /api/v1/postcode-lookup:
    parameters:
      - name: postcode
        in: query
        required: true
        schema:
          type: string
          nullable: false
    get:
      summary: Lookup addresses based on a post code
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  required:
                    - addressLine1
                    - addressLine2
                    - addressLine3
                    - town
                    - postcode
                    - description
                  properties:
                    addressLine1:
                      type: string
                      x-fake-data: Address.streetAddress
                    addressLine2:
                      type: string
                      x-fake-data: Address.streetName
                    addressLine3:
                      type: string
                      x-fake-data: Address.cityName
                    town:
                      type: string
                      x-fake-data: Address.cityName
                    postcode:
                      type: string
                      x-fake-data:
                        helpers.replaceSymbols: "??# #??"
                    description:
                      type: string
                      x-fake-data:
                        fake: "A concatenation of the address lines"

  /api/v1/lpa-lookup:
    parameters:
      - name: lpa
        in: query
        required: true
        schema:
          type: string
          nullable: false
          pattern: (M(-[A-Z0-9]{4}){3})
    get:
      summary: Lookup LPA based on an LPA reference
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CombinedLpa"
        "401":
          description: Error
  /api/v1/identity-check:
    post:
      operationId: postIdentityCheck
      summary: Manage Identity Check for Donor and / or Certificate Provider
      description: Manage Identity Check for Donor and / or Certificate Provider
      tags: [poa]
      requestBody:
        description: Incoming request for an identity check
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/IdentityCheckRequest"
      responses:
        "204":
          description: The identity check has been processed
        "400":
          description: Bad request
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/Error"

  /api/v1/lpas/{lpa}/documents:
    post:
      parameters:
        - name: lpa
          in: path
          required: true
          schema:
            type: integer
            nullable: false
      operationId: postCreateDocumentRequest
      summary: Send letter data
      description: Send data to create letter
      tags: [poa]
      requestBody:
        description: Sirius LPA document data
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateDocumentRequest"
      responses:
        "201":
          description: PDD data has been processed
        "400":
          description: Bad request
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/Error"

  /api/v1/persons/{donorId}/notes:
    post:
      parameters:
        - name: donorId
          in: path
          required: true
          schema:
            type: integer
            nullable: false
      operationId: postCreateNoteRequest
      summary: Add a note
      description: Add a note to a donors case record
      requestBody:
        description: Note data
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateNoteRequest"
      responses:
        "201":
          description: Note has been created
        "400":
          description: Bad request
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/Error"
  /api/v1/reference-data/country:
    get:
      summary: Lookup countries for address dropdown
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  required:
                    - handle
                    - label
                  properties:
                    handle:
                      type: string
                      x-fake-data: Address.countryCode
                    label:
                      type: string
                      x-fake-data: Address.country

components:
  schemas:
    User:
      type: object
      properties:
        email: string
    CombinedLpa:
      type: object
      required:
        - opg.poas.sirius
        - opg.poas.lpastore
      properties:
        opg.poas.sirius:
          $ref: "#/components/schemas/DigitalLpa"
        opg.poas.lpastore:
          oneOf:
            - allOf:
                - $ref: https://raw.githubusercontent.com/ministryofjustice/opg-data-lpa-store/main/docs/schemas/2024-10/lpa.json
                - $ref: "#/components/schemas/LpaWithPostcodes"
            - null
      additionalProperties: false
    DigitalLpa:
      type: object
      required:
        - id
        - uId
        - donor
      properties:
        id:
          type: integer
          minimum: 1
        uId:
          type: string
          pattern: "M(-[0-9A-Z]{4}){3}"
          example: M-789Q-P4DF-4UX3
        caseSubtype:
          type: string
          enum: [personal-welfare, property-and-affairs]
        donor:
          required: [firstname, surname, dob, addressLine1, town, postcode]
          type: object
          properties:
            firstname:
              type: string
              x-fake-data: Name.firstName
            surname:
              type: string
              x-fake-data: Name.lastName
            dob:
              type: string
              pattern: "[0-9]{1,2}/[0-9]{1,2}/[0-9]{4}"
              example: "01/01/1960"
            addressLine1:
              type: string
              x-fake-data: Address.streetAddress
            addressLine2:
              type: string
              x-fake-data: Address.streetName
            addressLine3:
              type: string
              x-fake-data: Address.cityName
            town:
              type: string
              x-fake-data: Address.cityName
            postcode:
              type: string
              example: "AB1 C23"
            country:
              type: string
              format: ISO-3166-1
              minLength: 2
              maxLength: 2
              x-fake-data: Address.countryCode
    LpaWithPostcodes:
      type: object
      properties:
        donor:
          type: object
          properties:
            address:
              type: object
              required:
                - postcode
        certificateProvider:
          type: object
          properties:
            address:
              type: object
              required:
                - postcode
    IdentityCheckRequest:
      type: object
      required:
        - actorType
        - lpaIds
        - time
        - outcome
      properties:
        reference:
          type: string
          format: uuid
        actorType:
          type: string
          enum:
            - donor
            - certificateProvider
        lpaIds:
          type: array
          items:
            type: string
            pattern: "M(-[0-9A-Z]{4}){3}"
        time:
          type: string
          format: date-time
        outcome:
          type: string
          enum:
            - success
            - exit
      additionalProperties: false
    CreateDocumentRequest:
      type: object
      required:
        - systemType
        - correspondentName
      properties:
        type:
          type: string
        systemType:
          type: string
        content:
          type: string
        pdfSuffix:
          type: string
        correspondentName:
          type: string
        correspondentAddress:
          type: array
    CreateNoteRequest:
      type: object
      required:
        - ownerId
        - ownerType
        - name
        - type
        - description
      properties:
        ownerId:
          type: string
        ownerType:
          type: string
        name:
          type: string
        type:
          type: string
        description:
          type: string
        donorFirstNames:
          type: string
        donorLastName:
          type: string
    Error:
      type: object
      required:
        - title
        - status
        - detail
      properties:
        type:
          type: string
          format: url
        title:
          type: string
        status:
          type: integer
        detail:
          type: string
        validation_errors:
          type: object
      additionalProperties: false
