openapi: 3.0.0
info:
  title: Notifications API
  description: Backwards engineered and limited to what we need to mock; deprecate if notifications provide an api spec
  version: 0.1.0
servers:
  - url: http://localhost:4010
    description: Local Prism server
paths:
  /api/v1/users/current:
    get:
      summary: Get current user
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '401':
          description: Error
components:
  schemas:
    User:
      type: object
      properties:
        id: int
