plugin: openapi
specFile: openapi.yml

resources:
  - path: "/api/v1/digital-lpas/M-XYXY-YAGA-35G3"
    method: get
    response:
      statusCode: 200
      scriptFile: useDonorJsonFile.groovy

  - path: "/api/v1/digital-lpas/M-XYXY-YAGA-0000"
    method: get
    response:
      statusCode: 200
      scriptFile: useCertificateProviderJsonFile.groovy

  - path: "/api/v1/users/current"
    method: get
    response:
      statusCode: 200
      scriptFile: useUserJsonFile.groovy
