plugin: openapi
specFile: openapi.yml

resources:
  - path: "/api/v1/digital-lpas/M-XYXY-YAGA-35G3"
    method: get
    response:
      statusCode: 200
      scriptFile: useDonorJsonFile.groovy

  - path: "/api/v1/digital-lpas/M-XYXY-YAGA-35G4"
    method: get
    response:
      statusCode: 200
      scriptFile: useDonorJsonFileNoDecision.groovy

  - path: "/api/v1/digital-lpas/M-XYXY-YAGA-35G5"
    method: get
    response:
      statusCode: 200
      scriptFile: useDonorJsonFileNoDecisionKBV.groovy

  - path: "/api/v1/digital-lpas/M-XYXY-YAGA-35G0"
    method: get
    response:
      statusCode: 200
      scriptFile: useDonorJsonFileStop.groovy

  - path: "/api/v1/digital-lpas/M-XYXY-YAGA-35F0"
    method: get
    response:
      statusCode: 200
      file: data/donorRefer.json

  - path: "/api/v1/digital-lpas/M-XYXY-YAGA-0000"
    method: get
    response:
      statusCode: 200
      scriptFile: useCertificateProviderJsonFile.groovy

  - path: "/api/v1/digital-lpas/M-XYXY-YAGA-0001"
    method: get
    response:
      statusCode: 200
      scriptFile: useCertificateProviderJsonFileNoDecision.groovy

  - path: "/api/v1/digital-lpas/M-XYXY-YAGA-0010"
    method: get
    response:
      statusCode: 200
      scriptFile: useCertificateProviderJsonFileNoDecisionKBV.groovy

  - path: "/api/v1/digital-lpas/M-XYXY-YAGA-0002"
    method: get
    response:
      statusCode: 200
      scriptFile: useCertificateProviderJsonFileStop.groovy
