plugin: openapi
specFile: openapi.yml

resources:
  - path: "/api/v1/postcode-lookup"
    method: get
    queryParams:
      postcode: SW1A1AA
    response:
      statusCode: 200
      file: data/addressResponse.json

  - path: "/api/v1/users/current"
    method: get
    response:
      statusCode: 200
      file: data/currentUser.json

  - path: "/api/v1/reference-data/country"
    method: get
    response:
      statusCode: 200
      file: data/countryListResponse.json

  - path: "/api/v1/digital-lpas/M-XYXY-YAGA-35G3"
    method: get
    response:
      statusCode: 200
      file: data/donor.json

  - path: "/api/v1/digital-lpas/M-XYXY-YAGB-35G3"
    method: get
    response:
      statusCode: 200
      file: data/donor.json

  - path: "/api/v1/digital-lpas/M-XYXY-YAGA-35G4"
    method: get
    response:
      statusCode: 200
      file: data/donorNoDecision.json

  - path: "/api/v1/digital-lpas/M-XYXY-YAGA-35G5"
    method: get
    response:
      statusCode: 200
      file: data/donorNoDecisionKBV.json

  - path: "/api/v1/digital-lpas/M-XYXY-YAGA-35G0"
    method: get
    response:
      statusCode: 200
      file: data/donorStop.json

  - path: "/api/v1/digital-lpas/M-XYXY-YAGA-35F0"
    method: get
    response:
      statusCode: 200
      file: data/donorRefer.json

  - path: "/api/v1/digital-lpas/M-XYXY-YAGA-DDWP"
    method: get
    response:
      statusCode: 200
      file: data/donorDwp.json

  - path: "/api/v1/digital-lpas/M-XYXY-YAGA-0000"
    method: get
    response:
      statusCode: 200
      file: data/certificateProvider.json

  - path: "/api/v1/digital-lpas/M-XYXY-YAGB-0000"
    method: get
    response:
      statusCode: 200
      file: data/certificateProvider.json

  - path: "/api/v1/digital-lpas/M-XYXY-YAGA-0001"
    method: get
    response:
      statusCode: 200
      file: data/certificateProviderNoDecision.json

  - path: "/api/v1/digital-lpas/M-XYXY-YAGA-0010"
    method: get
    response:
      statusCode: 200
      file: data/certificateProviderNoDecisionKBV.json

  - path: "/api/v1/digital-lpas/M-XYXY-YAGA-0002"
    method: get
    response:
      statusCode: 200
      file: data/certificateProviderStop.json

  - path: "/api/v1/digital-lpas/M-VOUC-HFOR-1001"
    method: get
    response:
      statusCode: 200
      file: data/voucherAddDonor.json

  - path: "/api/v1/digital-lpas/M-VOUC-HFOR-1002"
    method: get
    response:
      statusCode: 200
      file: data/voucherAddDonorLinked.json

  - path: "/api/v1/digital-lpas/M-VOUC-HFOR-2001"
    method: get
    response:
      statusCode: 200
      file: data/voucherAddAnotherDonor.json

  - path: "/api/v1/digital-lpas/M-VOUC-HFOR-3001"
    method: get
    response:
      statusCode: 200
      file: data/voucherAddDonorComplete.json

  - path: "/api/v1/digital-lpas/M-VOUC-HFOR-3002"
    method: get
    response:
      statusCode: 200
      file: data/voucherAddDonorDraft.json

  - path: "/api/v1/digital-lpas/M-VOUC-HFOR-3003"
    method: get
    response:
      statusCode: 200
      file: data/voucherAddDonorStatus.json

  - path: "/api/v1/digital-lpas/M-VOUC-HFOR-3004"
    method: get
    response:
      statusCode: 200
      file: data/voucherAddDonorLinkedStatus.json

  - path: "/api/v1/digital-lpas/M-DRAF-TLPA-35G3"
    method: get
    response:
      statusCode: 200
      file: data/donorDraft.json

  - path: "/api/v1/digital-lpas/M-DRAF-TLPA-CPG3"
    method: get
    response:
      statusCode: 200
      file: data/cpDraft.json

  - path: "/api/v1/digital-lpas/M-REGI-STER-DLPA"
    method: get
    response:
      statusCode: 200
      file: data/cpRegistered.json

  - path: "/api/v1/digital-lpas/M-DRAF-TLPA-35G3"
    method: get
    response:
      statusCode: 200
      file: data/donorDraft.json

  - path: "/api/v1/digital-lpas/M-DRAF-TLPA-CPG3"
    method: get
    response:
      statusCode: 200
      file: data/cpDraft.json

  - path: "/api/v1/digital-lpas/M-EMPT-YLPA-CPG3"
    method: get
    response:
      statusCode: 200
      file: data/cpEmpty.json

  - path: "/api/v1/digital-lpas/M-INPR-OGRE-CPG3"
    method: get
    response:
      statusCode: 200
      file: data/cpInProgress.json

  - path: "/api/v1/digital-lpas/M-CANC-ELLE-DPG3"
    method: get
    response:
      statusCode: 200
      file: data/cpCancelled.json

  - path: "/api/v1/digital-lpas/M-NOTR-EGIS-RPG3"
    method: get
    response:
      statusCode: 200
      file: data/cpCannotRegister.json

  - path: "/api/v1/digital-lpas/M-DERE-GIST-RPG3"
    method: get
    response:
      statusCode: 200
      file: data/cpDeRegistered.json

  - path: "/api/v1/digital-lpas/M-DNOT-REGI-RPG3"
    method: get
    response:
      statusCode: 200
      file: data/cpDoNotRegister.json

  - path: "/api/v1/digital-lpas/M-EXPI-REDQ-RPG3"
    method: get
    response:
      statusCode: 200
      file: data/cpExpired.json

  - path: "/api/v1/digital-lpas/M-STAT-WAIT-RPG3"
    method: get
    response:
      statusCode: 200
      file: data/cpStatWaitPeriod.json

  - path: "/api/v1/digital-lpas/M-SUSP-ENDE-DPG3"
    method: get
    response:
      statusCode: 200
      file: data/cpSuspended.json

  - path: "/api/v1/digital-lpas/*"
    method: get
    response:
      statusCode: 404
      file: data/lpa404.json
