plugin: openapi
specFile: openapi.yml

resources:
  - path: "/api/v1/postcode-lookup"
    method: get
    queryParams:
      postcode: SW1A1AA
    response:
      statusCode: 200
      file: data/addressResponse.json

  - path: "/api/v1/reference-data/country"
    method: get
    response:
      statusCode: 200
      file: data/countryListResponse.json

  - path: "/api/v1/digital-lpas/M-XYXY-YAGA-35G3"
    method: get
    response:
      statusCode: 200
      file: data/donor.json

  - path: "/api/v1/digital-lpas/M-XYXY-YAGB-35G3"
    method: get
    response:
      statusCode: 200
      file: data/donor.json

  - path: "/api/v1/digital-lpas/M-XYXY-YAGA-35G4"
    method: get
    response:
      statusCode: 200
      file: data/donorNoDecision.json

  - path: "/api/v1/digital-lpas/M-XYXY-YAGA-35G5"
    method: get
    response:
      statusCode: 200
      file: data/donorNoDecisionKBV.json

  - path: "/api/v1/digital-lpas/M-XYXY-YAGA-35G0"
    method: get
    response:
      statusCode: 200
      file: data/donorStop.json

  - path: "/api/v1/digital-lpas/M-XYXY-YAGA-35F0"
    method: get
    response:
      statusCode: 200
      file: data/donorRefer.json

  - path: "/api/v1/digital-lpas/M-XYXY-YAGA-0000"
    method: get
    response:
      statusCode: 200
      file: data/certificateProvider.json

  - path: "/api/v1/digital-lpas/M-XYXY-YAGB-0000"
    method: get
    response:
      statusCode: 200
      file: data/certificateProvider.json

  - path: "/api/v1/digital-lpas/M-XYXY-YAGA-0001"
    method: get
    response:
      statusCode: 200
      file: data/certificateProviderNoDecision.json

  - path: "/api/v1/digital-lpas/M-XYXY-YAGA-0010"
    method: get
    response:
      statusCode: 200
      file: data/certificateProviderNoDecisionKBV.json

  - path: "/api/v1/digital-lpas/M-XYXY-YAGA-0002"
    method: get
    response:
      statusCode: 200
      file: data/certificateProviderStop.json

  - path: "/api/v1/digital-lpas/M-VOUC-HFOR-1001"
    method: get
    response:
      statusCode: 200
      file: data/voucherAddDonor.json

  - path: "/api/v1/digital-lpas/M-VOUC-HFOR-1002"
    method: get
    response:
      statusCode: 200
      file: data/voucherAddDonorLinked.json

  - path: "/api/v1/digital-lpas/M-VOUC-HFOR-2001"
    method: get
    response:
      statusCode: 200
      file: data/voucherAddAnotherDonor.json

  - path: "/api/v1/digital-lpas/M-VOUC-HFOR-3001"
    method: get
    response:
      statusCode: 200
      file: data/voucherAddDonorComplete.json

  - path: "/api/v1/digital-lpas/M-VOUC-HFOR-3002"
    method: get
    response:
      statusCode: 200
      file: data/voucherAddDonorDraft.json

  - path: "/api/v1/digital-lpas/M-VOUC-HFOR-3003"
    method: get
    response:
      statusCode: 200
      file: data/voucherAddDonorStatus.json

  - path: "/api/v1/digital-lpas/M-VOUC-HFOR-3004"
    method: get
    response:
      statusCode: 200
      file: data/voucherAddDonorLinkedStatus.json

  - path: "/api/v1/digital-lpas/M-0000-0000-XXXX"
    method: get
    response:
      statusCode: 404

  - path: "/api/v1/digital-lpas/M-DRAF-TLPA-35G3"
    method: get
    response:
      statusCode: 200
      file: data/donorDraft.json

  - path: "/api/v1/digital-lpas/M-DRAF-TLPA-CPG3"
    method: get
    response:
      statusCode: 200
      file: data/cpDraft.json

  - path: "/api/v1/digital-lpas/M-REGI-STER-DLPA"
    method: get
    response:
      statusCode: 200
      file: data/cpRegistered.json
