plugin: openapi
specFile: openapi.yml

resources:
  - path: "/api/v1/postcode-lookup"
    method: get
    queryParams:
      postcode: SW1A1AA
    response:
      statusCode: 200
      file: data/addressResponse.json

  - path: "/api/v1/digital-lpas/M-XYXY-YAGA-35G3"
    method: get
    response:
      statusCode: 200
      file: data/donor.json

  - path: "/api/v1/digital-lpas/M-XYXY-YAGA-35G4"
    method: get
    response:
      statusCode: 200
      file: data/donorNoDecision.json

  - path: "/api/v1/digital-lpas/M-XYXY-YAGA-35G5"
    method: get
    response:
      statusCode: 200
      file: data/donorNoDecisionKBV.json

  - path: "/api/v1/digital-lpas/M-XYXY-YAGA-35G0"
    method: get
    response:
      statusCode: 200
      file: data/donorStop.json

  - path: "/api/v1/digital-lpas/M-XYXY-YAGA-0000"
    method: get
    response:
      statusCode: 200
      file: data/certificateProvider.json

  - path: "/api/v1/digital-lpas/M-XYXY-YAGA-0001"
    method: get
    response:
      statusCode: 200
      file: data/certificateProviderNoDecision.json

  - path: "/api/v1/digital-lpas/M-XYXY-YAGA-0010"
    method: get
    response:
      statusCode: 200
      file: data/certificateProviderNoDecisionKBV.json

  - path: "/api/v1/digital-lpas/M-XYXY-YAGA-0002"
    method: get
    response:
      statusCode: 200
      file: data/certificateProviderStop.json
