<div class="govuk-width-container">
    <main class="govuk-main-wrapper">
        <h1 class="govuk-heading-xl">Is the caller prepared to perform the ID check?</h1>

        <p class="govuk-body">
            Things to check:
        </p>
        <ul class="govuk-list govuk-list--bullet">
            <li>
                how will they ID?
            </li>
            <li>
                do they have their ID document with them?
            </li>
            <li>
                does the name / dob on their ID document match what is in Sirius?
            </li>
            <li>
                are they ready to answer any questions they might have?
            </li>
            <li>
                CP / voucher: do they have other LPAs they’ll need to do an ID check for?
            </li>
        </ul>

        <details class="govuk-details">
            <summary class="govuk-details__summary">
                <span class="govuk-details__summary-text">
                  ID over the phone
                </span>
            </summary>
            <div class="govuk-details__text">
                <?php
                foreach ($this->data as $datum) {
                    echo '<h2 class="govuk-heading-m">' . $this->escapeHtml($datum) . '</h2>';
                }
                ?>
            </div>
        </details>

        <details class="govuk-details">
            <summary class="govuk-details__summary">
    <span class="govuk-details__summary-text">
      ID in person at the Post Office
    </span>
            </summary>
            <div class="govuk-details__text">
            </div>
        </details>

        <details class="govuk-details">
            <summary class="govuk-details__summary">
    <span class="govuk-details__summary-text">
      No ID: Choose someone to vouch (donor only)
    </span>
            </summary>
            <div class="govuk-details__text">
            </div>
        </details>

        <details class="govuk-details">
            <summary class="govuk-details__summary">
    <span class="govuk-details__summary-text">
      Court of Protection (donor only)
    </span>
            </summary>
            <div class="govuk-details__text">
            </div>
        </details>

        <button class="govuk-button">Continue</button>

    </main>
</div>
