plugin: openapi
specFile: openapi.yml-bk

resources:
  - path: "/idverify/v1/sessions/{sessionId}"
    method: get
    response:
      statusCode: 200
      scriptFile: useJsonFile.groovy

  - path: "/idverify/v1/lookup/uk-post-office"
    method: post
    response:
      statusCode: 200
      scriptFile: useBranchesFile.groovy
