plugin: openapi
specFile: openapi.yml

resources:
  - path: "/idverify/v1/sessions/{sessionId}"
    method: get
    response:
      statusCode: 200
      scriptFile: useJsonFile.groovy

  - path: "/idverify/v1/lookup/uk-post-office"
    method: post
    response:
      statusCode: 200
      scriptFile: useBranchesFile.groovy

  - path: "/idverify/v1/sessions/{sessionId}/configuration"
    method: get
    response:
      statusCode: 200
      scriptFile: letterConfiguration.groovy

  - path: "/idverify/v1/sessions/{sessionId}/media/{mediaId}/content"
    method: get
    response:
      statusCode: 200
      scriptFile: mediaRetrieval.groovy
