plugin: openapi
specFile: openapi.yml

resources:
  - path: "/idverify/v1/sessions/{sessionId}"
    method: get
    response:
      statusCode: 200
      scriptFile: useJsonFile.groovy

  - path: "/idverify/v1/lookup/uk-post-office"
    method: post
    requestBody:
      jsonPath: $.search_string
      value: SW1A
      operator: NotContains
    response:
      statusCode: 200
      file: data/branchesOne.json

  - path: "/idverify/v1/lookup/uk-post-office"
    method: post
    requestBody:
      jsonPath: $.search_string
      value: SW1A
      operator: Contains
    response:
      statusCode: 200
      file: data/branchesTwo.json

  - path: "/idverify/v1/sessions/{sessionId}/configuration"
    method: get
    response:
      statusCode: 200
      scriptFile: letterConfiguration.groovy

  - path: "/idverify/v1/sessions/{sessionId}/media/{mediaId}/content"
    method: get
    response:
      statusCode: 200
      scriptFile: mediaRetrieval.groovy
